import React from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  ArrowRight, 
  Sparkles, 
  ShieldCheck, 
  Zap, 
  BarChart3, 
  Cpu,
  Brain,
  Plus,
  Play,
  CheckCircle2,
  TrendingUp,
  Target,
  Layers,
  ArrowUpRight
} from 'lucide-react';
import Button from '../../../components/ui/Button';

const Home = () => {
  const navigate = useNavigate();

  const features = [
    { 
      title: 'Neural Match Engine', 
      desc: 'Our AI doesn\'t just search keywords; it understands semantic intent, experience depth, and potential.',
      icon: Brain,
      color: 'text-blue-500'
    },
    { 
      title: 'ATS Command Center', 
      desc: 'Real-time resume scoring with precise gap analysis and upskilling paths generated by Ollama.',
      icon: Target,
      color: 'text-emerald-500'
    },
    { 
      title: 'Semantic Job Discovery', 
      desc: 'Discover roles that align with your career trajectory using deep-learning recommendation logic.',
      icon: Zap,
      color: 'text-amber-500'
    }
  ];

  return (
    <div className="relative overflow-hidden bg-white dark:bg-[#0a0f14] transition-colors duration-500">
      
      {/* ═══ BACKGROUND AESTHETICS ═══════════════════════════════════════════ */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[1000px] pointer-events-none z-0">
         <div className="absolute top-[-10%] left-[-10%] size-[600px] bg-primary/20 blur-[120px] rounded-full animate-pulse" />
         <div className="absolute top-[20%] right-[-10%] size-[500px] bg-indigo-500/10 blur-[100px] rounded-full" />
      </div>

      {/* ═══ HERO SECTION ═══════════════════════════════════════════════ */}
      <section className="relative z-10 pt-32 pb-20 px-6 overflow-hidden">
        <div className="max-w-[1400px] mx-auto grid grid-cols-1 lg:grid-cols-2 gap-20 items-center">
          
          <div className="space-y-12 animate-in fade-in slide-in-from-left-8 duration-1000">
            <div className="space-y-6">
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/5 border border-primary/10 rounded-full">
                 <Sparkles size={14} className="text-primary" />
                 <span className="text-[10px] font-black uppercase tracking-[0.2em] text-primary">v2.0 — AI Recruitment Engine</span>
              </div>
              <h1 className="text-6xl md:text-7xl lg:text-8xl font-black text-gray-900 dark:text-white leading-[0.9] tracking-tighter">
                The Operating System for <span className="bg-gradient-to-r from-primary to-indigo-600 bg-clip-text text-transparent">Modern Careers.</span>
              </h1>
              <p className="text-xl text-gray-500 dark:text-gray-400 font-medium max-w-xl leading-relaxed">
                LINKUP synchronizes candidate potential with employer intelligence using neural matching. Zero friction. Maximum alignment.
              </p>
            </div>
            
            <div className="flex flex-wrap items-center gap-6">
              <Button 
                onClick={() => navigate('/auth/signup?role=jobseeker')}
                className="h-16 px-10 text-base rounded-2xl shadow-2xl shadow-primary/30 group"
                variant="primary"
              >
                Get Started
                <ArrowRight size={18} className="ml-2 transition-transform group-hover:translate-x-1" />
              </Button>
              <Button 
                onClick={() => navigate('/auth/login')}
                className="h-16 px-10 text-base rounded-2xl border-gray-100 dark:border-gray-800 bg-white/50 dark:bg-gray-900/50 backdrop-blur-xl text-gray-900 dark:text-white hover:bg-white dark:hover:bg-gray-900 transition-all shadow-sm"
                variant="outline"
              >
                Sign In
              </Button>
            </div>

            <div className="flex items-center gap-8 pt-8 border-t border-gray-50 dark:border-gray-900">
               <div>
                  <p className="text-sm font-black text-gray-900 dark:text-white uppercase tracking-widest">24.2k</p>
                  <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mt-1">Global Hires</p>
               </div>
               <div className="w-px h-10 bg-gray-50 dark:bg-gray-800" />
               <div>
                  <p className="text-sm font-black text-gray-900 dark:text-white uppercase tracking-widest">82%</p>
                  <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mt-1">Match Accuracy</p>
               </div>
               <div className="w-px h-10 bg-gray-50 dark:bg-gray-800" />
               <div>
                  <p className="text-sm font-black text-gray-900 dark:text-white uppercase tracking-widest">Enterprise</p>
                  <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mt-1">SLA Verified</p>
               </div>
            </div>
          </div>

          {/* AI WORKSPACE PREVIEW */}
          <div className="relative animate-in fade-in slide-in-from-right-8 duration-1000 delay-200">
            {/* Floating Glass Element */}
            <div className="absolute -top-10 -left-10 z-20 p-6 bg-white/80 dark:bg-gray-900/80 backdrop-blur-2xl rounded-3xl border border-white/20 dark:border-gray-800 shadow-2xl space-y-3 animate-bounce-slow">
               <div className="flex items-center gap-3">
                  <div className="size-8 bg-emerald-500/20 rounded-lg flex items-center justify-center text-emerald-500">
                     <CheckCircle2 size={16} />
                  </div>
                  <span className="text-[10px] font-black uppercase tracking-widest">Profile Verified</span>
               </div>
               <p className="text-sm font-bold text-gray-900 dark:text-white">Arjun R. • Senior AI</p>
            </div>

            <div className="card-premium p-1 p-[1px] bg-gradient-to-br from-primary/50 to-indigo-500/50 rounded-[2.5rem]">
               <div className="bg-white dark:bg-[#0c1219] rounded-[2.5rem] overflow-hidden p-8 space-y-8">
                  <div className="flex items-center justify-between pb-6 border-b border-gray-50 dark:border-gray-800">
                     <div className="flex items-center gap-4">
                        <div className="size-12 bg-primary/10 rounded-2xl flex items-center justify-center text-primary border border-primary/20">
                           <Layers size={20} />
                        </div>
                        <div>
                           <p className="text-lg font-black text-gray-900 dark:text-white tracking-tight uppercase">Intelligence Center</p>
                           <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mt-0.5">Neural Rank: #1 candidate</p>
                        </div>
                     </div>
                  </div>

                  <div className="grid grid-cols-2 gap-6">
                     <div className="p-6 bg-primary/5 rounded-[2rem] border border-primary/10 flex flex-col items-center justify-center text-center">
                        <span className="text-[9px] font-black text-primary uppercase tracking-widest mb-2">ATS Accuracy</span>
                        <span className="text-5xl font-black text-primary tracking-tighter">94%</span>
                        <div className="flex items-center gap-1 mt-2 text-emerald-500">
                           <TrendingUp size={12} />
                           <span className="text-[9px] font-black uppercase tracking-widest">Exceptional</span>
                        </div>
                     </div>
                     <div className="space-y-4">
                        <span className="text-[9px] font-black text-gray-400 uppercase tracking-widest ml-1">Key Strengths</span>
                        <div className="space-y-2">
                           {['Natural Language', 'Vector DBs', 'Scalability'].map(s => (
                             <div key={s} className="px-4 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-100 dark:border-gray-800 rounded-xl text-[10px] font-bold text-gray-500 uppercase tracking-widest flex items-center gap-2">
                                <div className="size-1.5 bg-emerald-500 rounded-full" /> {s}
                             </div>
                           ))}
                        </div>
                     </div>
                  </div>

                  <div className="p-6 bg-gray-900 dark:bg-black rounded-3xl border border-gray-800 space-y-4 shadow-2xl">
                     <div className="flex items-center gap-3 text-primary">
                        <Zap size={16} />
                        <span className="text-[10px] font-black uppercase tracking-widest text-primary">AI Recommendation</span>
                     </div>
                     <p className="text-sm text-gray-400 font-medium leading-relaxed">
                        "Candidate shows deep expertise in <strong>RAG Architectures</strong>. Highly recommended for the Platform Engineer role."
                     </p>
                     <div className="pt-2">
                        <Button className="w-full rounded-2xl h-11 text-[10px] uppercase font-black tracking-widest">Initiate Interview</Button>
                     </div>
                  </div>
               </div>
            </div>
          </div>
        </div>
      </section>

      {/* ═══ TRUST / LOGO WALL ═══════════════════════════════════════════════ */}
      <section className="py-20 border-y border-gray-50 dark:border-gray-900 bg-gray-50/50 dark:bg-gray-900/20 backdrop-blur-sm">
         <div className="max-w-[1400px] mx-auto px-6">
            <p className="text-center text-[10px] font-black text-gray-400 uppercase tracking-[0.3em] mb-12">Empowering the world's most innovative teams</p>
            <div className="flex flex-wrap items-center justify-center gap-16 grayscale opacity-50 dark:invert">
               <span className="text-2xl font-black tracking-tighter">ZOHO</span>
               <span className="text-2xl font-black tracking-tighter italic">Stripe</span>
               <span className="text-2xl font-black tracking-tighter">Freshworks</span>
               <span className="text-2xl font-black tracking-tighter">Razorpay</span>
               <span className="text-2xl font-black tracking-tighter italic">CRED</span>
            </div>
         </div>
      </section>

      {/* ═══ FEATURES ═══════════════════════════════════════════════════════ */}
      <section className="py-32 px-6 max-w-[1400px] mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
          {features.map((f, i) => (
            <div key={i} className="space-y-6 group cursor-default">
              <div className={`size-16 rounded-[1.5rem] bg-white dark:bg-gray-900 border border-gray-50 dark:border-gray-800 shadow-xl flex items-center justify-center transition-all duration-500 group-hover:scale-110 group-hover:-rotate-3 group-hover:border-primary/30 ${f.color}`}>
                <f.icon size={28} />
              </div>
              <div className="space-y-3">
                <h3 className="text-2xl font-black text-gray-900 dark:text-white tracking-tight uppercase">{f.title}</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 font-medium leading-relaxed">{f.desc}</p>
              </div>
              <button className="flex items-center gap-2 text-[10px] font-black text-primary uppercase tracking-widest opacity-0 group-hover:opacity-100 transition-opacity">
                 Learn More <ArrowUpRight size={14} />
              </button>
            </div>
          ))}
        </div>
      </section>

      {/* ═══ CTA SECTION ═══════════════════════════════════════════════════ */}
      <section className="py-20 px-6 max-w-[1400px] mx-auto">
         <div className="relative p-1 p-[1px] bg-gradient-to-r from-primary/50 via-indigo-500/50 to-primary/50 rounded-[3rem] overflow-hidden group">
            <div className="absolute inset-0 bg-primary/20 opacity-0 group-hover:opacity-100 blur-[80px] transition-opacity duration-1000" />
            <div className="relative z-10 bg-white dark:bg-[#0c1219] rounded-[3rem] p-20 flex flex-col items-center text-center space-y-12">
               <div className="space-y-6 max-w-3xl">
                  <h2 className="text-5xl md:text-6xl font-black text-gray-900 dark:text-white leading-tight tracking-tighter">
                     Ready to define the <span className="text-primary italic">future</span> of recruitment?
                  </h2>
                  <p className="text-lg text-gray-500 dark:text-gray-400 font-medium">
                     Join thousands of elite professionals and high-growth companies building the recruitment OS of tomorrow.
                  </p>
               </div>
               
               <div className="flex flex-wrap items-center justify-center gap-6">
                  <Button 
                     onClick={() => navigate('/auth/signup?role=jobseeker')}
                     className="h-16 px-12 text-base rounded-2xl shadow-xl shadow-primary/20"
                  >
                     Start Free Trial
                  </Button>
                  <Button 
                     variant="secondary"
                     className="h-16 px-12 text-base rounded-2xl border-gray-100 dark:border-gray-800 text-gray-900 dark:text-white"
                  >
                     Contact Sales
                  </Button>
               </div>
            </div>
         </div>
      </section>

      {/* Footer Meta */}
      <footer className="py-12 px-6 border-t border-gray-50 dark:border-gray-900 max-w-[1400px] mx-auto flex flex-col md:flex-row items-center justify-between gap-8">
         <div className="flex items-center gap-2">
            <div className="size-8 bg-primary rounded-xl flex items-center justify-center text-white">
               <Zap size={16} />
            </div>
            <span className="text-lg font-black text-gray-900 dark:text-white uppercase tracking-tighter">LINKUP</span>
         </div>
         <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">© 2026 LINKUP RECRUITMENT TECHNOLOGIES. ALL RIGHTS RESERVED.</p>
         <div className="flex items-center gap-8 text-[10px] font-black text-gray-400 uppercase tracking-widest">
            <span className="hover:text-primary cursor-pointer transition-colors">Privacy</span>
            <span className="hover:text-primary cursor-pointer transition-colors">Terms</span>
            <span className="hover:text-primary cursor-pointer transition-colors">Security</span>
         </div>
      </footer>

    </div>
  );
};

export default Home;
