import React, { useEffect, useState } from 'react';
import { 
  BookOpen, 
  Award, 
  Code, 
  ExternalLink, 
  PlayCircle, 
  ArrowRight, 
  Loader,
  Zap,
  Sparkles,
  Milestone,
  CheckCircle2,
  GraduationCap
} from 'lucide-react';
import Button from '../../../components/ui/Button';
import { getCurrentUserId } from '../../../core/auth/session';
import { fetchLearningRecommendations } from '../services/jobseekerService';

// Shared Components
import PageHeader from '../../../components/shared/PageHeader';
import SectionTitle from '../../../components/shared/SectionTitle';
import LoadingSkeleton from '../../../components/shared/LoadingSkeleton';

export default function Learning() {
  const userId = getCurrentUserId();
  const [data, setData] = useState({ courses: [], roadmap: [], certifications: [] });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        if (userId) {
          const res = await fetchLearningRecommendations(userId);
          setData(res.learning || { courses: [], roadmap: [], certifications: [] });
        }
      } catch (err) {
        console.error("Failed to fetch learning recommendations:", err);
      } finally {
        setLoading(false);
      }
    };
    loadData();
  }, [userId]);

  if (loading) {
    return (
      <div className="space-y-8 pt-4">
        <LoadingSkeleton type="header" />
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
           <div className="lg:col-span-8 space-y-8">
              <LoadingSkeleton type="card" count={2} />
           </div>
           <div className="lg:col-span-4">
              <LoadingSkeleton type="card" count={3} />
           </div>
        </div>
      </div>
    );
  }

  const { courses, roadmap, certifications } = data;

  return (
    <div className="space-y-10 pt-4 pb-20 animate-in fade-in slide-in-from-bottom-4 duration-700">
      
      <PageHeader 
        title="Intelligence Academy" 
        subtitle="Personalized learning paths generated by AI to bridge your technical gaps."
        breadcrumbs={["Platform", "Jobseeker", "Learning"]}
      />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-start">
        
        {/* LEFT COLUMN: Roadmap & Courses */}
        <div className="lg:col-span-8 space-y-12">
          
          {/* SKILL ROADMAP - VERTICAL PATH */}
          <section className="space-y-6">
            <SectionTitle 
              title="Path of Growth" 
              description="A structured sequence to reach your next career milestone."
            />
            
            <div className="relative pl-8 space-y-8 before:absolute before:left-[11px] before:top-2 before:bottom-2 before:w-0.5 before:bg-gray-100 dark:before:bg-gray-800">
              {roadmap.map((item, idx) => (
                <div key={idx} className="relative group">
                   {/* Node Circle */}
                   <div className={`absolute -left-[29px] top-1.5 size-4 rounded-full border-2 border-white dark:border-[#0a0f14] z-10 transition-all duration-500 group-hover:scale-125 ${
                     idx === 0 ? 'bg-primary shadow-[0_0_10px_rgba(37,99,235,0.5)]' : 'bg-gray-200 dark:bg-gray-700'
                   }`} />
                   
                   <div className="card-premium p-6 hover:border-primary/30 transition-all">
                      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                         <div className="space-y-2">
                            <div className="flex items-center gap-2">
                               <h3 className="text-sm font-black text-gray-900 dark:text-white uppercase tracking-tight">{item.title}</h3>
                               <span className="text-[9px] font-black text-primary bg-primary/5 px-2 py-0.5 rounded-full uppercase tracking-widest border border-primary/10">
                                  {item.milestone || 'In Progress'}
                               </span>
                            </div>
                            <p className="body-sm text-gray-500 leading-relaxed max-w-xl">{item.description}</p>
                            <div className="flex flex-wrap gap-2 pt-1">
                               {(item.skills || []).map(s => (
                                 <span key={s} className="px-2 py-0.5 bg-gray-50 dark:bg-gray-900 text-gray-500 dark:text-gray-400 rounded-md text-[10px] font-bold uppercase tracking-widest border border-gray-100 dark:border-gray-800">
                                   {s}
                                 </span>
                               ))}
                            </div>
                         </div>
                         <Button variant="secondary" className="rounded-xl h-9 px-6 text-[10px] font-black uppercase tracking-widest shrink-0">
                           Initialize
                         </Button>
                      </div>
                   </div>
                </div>
              ))}
            </div>
          </section>

          {/* RECOMMENDED COURSES */}
          <section className="space-y-6 pt-6">
            <SectionTitle 
              title="Curated Curriculum" 
              description="High-impact resources specifically matched to your missing skills."
            />
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              {courses.map((course, idx) => (
                <div key={idx} className="card-premium p-6 group flex flex-col h-full border-l-4 border-l-primary/20 hover:border-l-primary transition-all">
                  <div className="flex-1 space-y-4">
                     <div className="flex items-center justify-between">
                        <div className="size-10 bg-primary/5 rounded-xl flex items-center justify-center text-primary group-hover:scale-110 transition-transform">
                           <PlayCircle size={20} />
                        </div>
                        <span className="text-[9px] font-black text-gray-400 uppercase tracking-widest">{course.provider || 'E-Learning'}</span>
                     </div>
                     <h3 className="text-base font-black text-gray-900 dark:text-white leading-tight tracking-tight uppercase group-hover:text-primary transition-colors">{course.title}</h3>
                     <div className="flex flex-wrap gap-2">
                        <span className="bg-gray-50 dark:bg-gray-900 px-3 py-1 rounded-full text-[10px] font-black text-gray-500 uppercase tracking-widest">{course.duration || 'Flexible'}</span>
                        <span className="bg-primary/5 text-primary px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest">{course.level || 'Intermediate'}</span>
                     </div>
                  </div>
                  <a href={course.url || "#"} target="_blank" rel="noreferrer" className="mt-6 w-full flex items-center justify-center gap-2 py-3 text-[10px] font-black text-gray-400 hover:text-primary uppercase tracking-widest rounded-xl hover:bg-primary/5 transition-all">
                    Access Portal <ExternalLink size={12} />
                  </a>
                </div>
              ))}
            </div>
          </section>

        </div>

        {/* RIGHT COLUMN: Certifications & Meta */}
        <div className="lg:col-span-4 space-y-8">
           
           <div className="card-premium p-8 space-y-6">
             <div className="flex items-center gap-3">
               <div className="size-12 bg-amber-500/10 text-amber-500 rounded-2xl flex items-center justify-center border border-amber-500/20">
                 <Award size={24} />
               </div>
               <div>
                  <h2 className="text-sm font-black text-gray-900 dark:text-white uppercase tracking-widest leading-none">Verifications</h2>
                  <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mt-1">Proof of expertise</p>
               </div>
             </div>
             
             <div className="space-y-4">
               {certifications.map((cert, idx) => (
                 <div key={idx} className="p-5 bg-gray-50 dark:bg-gray-900/50 border border-gray-100 dark:border-gray-800 rounded-2xl group cursor-pointer hover:border-amber-500/30 transition-all">
                    <h3 className="text-xs font-black text-gray-900 dark:text-white uppercase tracking-tight group-hover:text-amber-500 transition-colors">{cert.title}</h3>
                    <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-1">{cert.provider || cert.skill}</p>
                    <div className="flex items-center gap-1 mt-3 text-[9px] font-black text-amber-600 uppercase tracking-[0.2em] opacity-0 group-hover:opacity-100 transition-opacity">
                      Enroll now <ArrowRight size={10} />
                    </div>
                 </div>
               ))}
               {certifications.length === 0 && (
                 <div className="text-center py-8">
                    <GraduationCap size={32} className="mx-auto text-gray-200 dark:text-gray-800 mb-4" />
                    <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">No certifications found.</p>
                 </div>
               )}
             </div>
           </div>

           <div className="card-premium p-8 bg-gray-900 dark:bg-black border-gray-800 space-y-6">
              <div className="flex items-center gap-2 text-primary">
                 <Zap size={16} />
                 <span className="text-[10px] font-black uppercase tracking-widest">Growth Analytics</span>
              </div>
              <div className="space-y-4">
                 <div className="flex justify-between items-end">
                    <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Market Ready</span>
                    <span className="text-2xl font-black text-white leading-none tracking-tighter">72%</span>
                 </div>
                 <div className="h-1.5 w-full bg-gray-800 rounded-full overflow-hidden">
                    <div className="h-full bg-primary w-[72%] transition-all duration-1000" />
                 </div>
                 <p className="text-[10px] text-gray-500 font-medium leading-relaxed italic">
                    "Complete the <strong>RAG System Design</strong> course to reach 85% market readiness."
                 </p>
              </div>
           </div>

        </div>
      </div>
    </div>
  );
}
